### ISSUE TITLE
MVP 1 user story

### ISSUE THREAD

**Issue by cryos** [NSLS-II/project-management#27]
Implement the necessary user interface and user experience to facilitate MVP 1 visit. This will assume user has an accepted proposal, and is on their beamline visit day for a simple run using an approved Bluesky plan:

- [x] Present a simple view of the beamline
- [x] Show available plans
- [x] Select a plan
- [x] Show any variables that can be changed
- [x] Hit "the button" to acquire
- [x] Observe the acquisition
- [x] Get a UID for the run
- [ ] Get a bucket of UIDs for the day
- [x] View all runs for the day
- [x] Visual overview using PNG previews
- [ ] Download data

**Comment by JunAishima** [comment]
I'm in!

**Comment by cryos** [comment]
Deferring the bucket of UIDs for the day, and the download of the data for a future epic. We have achieved all of our core goals of MVP 1, and @tacaswell has created a short movie showing those achievements in the pods.
