### ISSUE TITLE
Realistic test on a real beamline

### ISSUE THREAD

**Issue by cryos** [NSLS-II/project-management#36]
Following on from MVP 1 select and test the approach on a real beamline. Preferably one that has been reIPed:

- [x] Select a beamline to prototype
- [x] Liaise with the beamline and discuss when and how we can test
- [x] Get to know the plans that will be tested
- [x] [Develop some UI](https://github.com/NSLS-II/project-management/issues/38)
- [x] Test the plan worker and ensure it can initialize, run a simple plan
- [x] Set up a queueserver instance, connect it to a worker, test plan execution
- [x] Connect the web interface to the queueserver instance, hit the button, acquire data
- [x] Consider other elements that might be connected, define success criteria

**Comment by mrakitin** [comment]
- [x] Select a beamline to prototype - picked up BMM.

**Comment by mrakitin** [comment]
- [ ] Liaise with the beamline and discuss when and how we can test - working on that, already sent an email to Bruce.

**Comment by mrakitin** [comment]
The 5 plans to intergate (from @bruceravel):
> 1. xafs()
> 2. linescan()
> 3. change_edge()
> 4. rocking_curve()
> 5. slit_height()
> 
> Together, those exercise pretty much 95% of what a user does at BMM.

**Comment by mrakitin** [comment]
Testing can happen ...
> Sometime after November 9 and before November 25.

**Comment by JunAishima** [comment]
sorry, didn't mean to close it. it was a bit clear whether it was the webpage interface or the actual issue (at least in my head)!

**Comment by cryos** [comment]
@dmgav and @tacaswell are we ready to try and run a simple plan on the worker, and possibly try out the queue manager? We have 9-25 November as a date range from initial communication.

**Comment by cryos** [comment]
This was done at BMM, plans were successfully executed, screenshots and photos were taken. The basic viability has been demonstrated. Follow up tests will look at doing this in more robust ways.
