### ISSUE TITLE
5LS Demo

### ISSUE THREAD

**Issue by mrakitin** [NSLS-II/project-management#39]
- [ ] Beautify XAS form https://github.com/bluesky/bluesky-webclient/issues/72
- [ ] General UI polish https://github.com/bluesky/bluesky-webclient/issues/73
- [x] Server logs (https server and manager) need to be quieter https://github.com/bluesky/bluesky-queueserver/issues/130
- [ ] Qt frontend to the RE worker https://github.com/NSLS-II/project-management/issues/40
- [x] Editable entries in the queue https://github.com/bluesky/bluesky-queueserver/issues/131
- [ ] Qt and Jupyter bluesky-widgets for LiveTable https://github.com/bluesky/bluesky-widgets/issues/108
- [ ] Qt and Jupyter bluesky-widgets for live images https://github.com/bluesky/bluesky-widgets/issues/109
- [ ] BMM viz, starting with add and removing lines https://github.com/bluesky/bluesky-widgets/issues/69
- [ ] Excel upload https://github.com/bluesky/bluesky-queueserver/issues/132
- [ ] Simulated profile for PDF
  - [ ] https://github.com/NSLS-II-PDF/profile_collection/pull/23
  - [x] https://github.com/NSLS-II-PDF/profile_collection/pull/24
- [ ] Reduce plans and devices to only those needed for the demo NSLS-II-PDF/profile_collection#23 (?)
- [x] Make sure a working kafka is visible to PDF and BMM https://github.com/NSLS-II/project-management/issues/41
- [x] Configure a backup Kafka https://github.com/NSLS-II/project-management/issues/42
- [ ] Figure out the fastest path to getting I(q)’s into bluesky-widgets https://github.com/NSLS-II/project-management/issues/43
- [ ] Material identification with xrdphase https://github.com/NSLS-II/project-management/issues/44 (optional?)

**Comment by mrakitin** [comment]
Closing in favor of https://jira.nsls2.bnl.gov/secure/RapidBoard.jspa?rapidView=1&projectKey=RDTF&selectedIssue=RDTF-30.
